#ifndef DATA_COMMOMDEF
#define DATA_COMMOMDEF

//#define STATIONID_COLUMN_NUMBER 0
#define IPADDRESS_COLUMN_NUMBER 0
#define STATUS_COLUMN_NUMBER 1
#define RATE_COLUMN_NUMBER 2



#endif // DATA_COMMOMDEF

